version: '3.7'
services:
  ui:
    build:
      dockerfile: docker/ui.Dockerfile
      context: ..
    volumes:
      - ../oerworldmap-ui:/srv/oerworldmap-ui
      - ./ui.env:/srv/oerworldmap-ui/.env
    ports:
      - 3000:3000

  pages:
    image: jekyll/jekyll:stable
    command: jekyll serve --watch --incremental
    environment:
      - JEKYLL_ENV=production
    volumes:
        - ../oerworldmap-ui/docs:/srv/jekyll
    ports:
        - 4000:4000

  scala:
    build:
      context: ..
      dockerfile: docker/scala.Dockerfile
    volumes:
      - ../oerworldmap-api:/srv/oerworldmap
      - ../cache/scala-homedir:/root
      - ./application.docker.conf:/srv/oerworldmap/conf/application.conf
    ports:
      - '9000:9000'
    depends_on:
      - elasticsearch
    # FIXME: `sbt run` dies when `< /dev/null` so we need to connect to the terminal, for now.
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  elasticsearch:
    build:
      dockerfile: docker/elasticsearch.Dockerfile
      context: ..
    expose:
      - 9200
